version: '3.9'

services:
    backend:
        image: v4runk/backend-example-docker
        build: .
        environment:
            REDIS_HOST: redis
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
            REQUEST_ORIGIN: http://localhost:80
        depends_on:
            - redis
            - postgres
    frontend:
        image: v4runk/frontend-example-docker
        build: .
        environment:
            REACT_APP_BACKEND_URL: http://localhost:80
    redis:
        container_name: redis
        image: redis
        restart: unless-stopped
    postgres:
        container_name: postgres
        image: postgres
        environment:
            # POSTGRES_PASSWORD is the only one required for database initialisation
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
