services:
    simple-web-service:
        image: devopsdockeruh/simple-web-service:ubuntu
        build: .
        volumes:
            - ./log.txt:/usr/src/app/text.log
        container_name: simple-web-service-composed
