services:
    backend:
        build: ./backend
        ports:
            - '8080:8080'
        environment:
            - PORT=8080
            - REQUEST_ORIGIN=http://localhost:5000

    frontend:
        build: ./frontend
        ports:
            - '5000:5000'
        environment:
            - REACT_APP_BACKEND_URL=http://localhost:8080
