services:
    backend:
        image: v4runk/backend-example-docker
        build: .
        ports:
            - '8080:8080'
        environment:
            - REQUEST_ORIGIN=http://localhost:5000

    frontend:
        image: v4runk/frontend-example-docker
        build: .
        ports:
            - '5000:5000'
        environment:
            - REACT_APP_BACKEND_URL=http://localhost:8080
