services:
    postgres:
        container_name: postgres
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST: postgres
            POSTGRES_DATABASE: postgres
        volumes:
            - ./database:/var/lib/postgresql/data
    backend:
        image: v4runk/backend-example-docker
        build: .
        ports:
            - 8080:8080
        environment:
            REQUEST_ORIGIN: http://localhost:5000
            REDIS_HOST: redis
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST: postgres
            POSTGRES_DATABASE: postgres
        depends_on:
            - redis
            - postgres

    frontend:
        image: v4runk/frontend-example-docker
        build: .
        ports:
            - 5000:5000
        environment:
            REACT_APP_BACKEND_URL: http://localhost:8080

    redis:
        container_name: redis
        image: redis
        restart: unless-stopped
