services:
    backend:
        image: v4runk/backend-example-docker
        ports:
            - '8080:8080'
        environment:
            - REDIS_HOST=redis
            - REQUEST_ORIGIN=http://localhost:5000
        depends_on:
            - redis

    frontend:
        image: v4runk/frontend-example-docker
        ports:
            - '5000:5000'
        environment:
            - REACT_APP_BACKEND_URL=http://localhost:8080
    redis:
        container_name: redis-cache
        image: redis
        restart: unless-stopped
